### ISSUE TITLE
Remote debugging openjdk:9

### ISSUE THREAD

**Issue by ydrozdov** [docker-library/openjdk#146]
I have a Dockerfile with this content:

```
FROM openjdk:9

WORKDIR /project

ADD . /project

EXPOSE 5005
```
My docker-compose.yml looks like this:

```
version: "3.2"
services:
  some-project:
    build: .
    ports:
      - target: 5005
        published: 5005
        protocol: tcp
        mode: host
  command: "java '-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005' SomeClass"
```
When I do **docker-composer up** I see a message "_Listening for transport dt_socket at address: 5005_". But when I try to connect with **jdb** or **Idea** I get "_java.io.IOException: handshake failed - connection prematurally closed_".

Everything works fine if I change **openjdk:9** to **openjdk:8**.
